// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8SveKZiQ1U9c9ZI_jW5NZ6WHQBSp3DDo',
    appId: '1:737285476811:web:6243389dd5b0a51b73264e',
    messagingSenderId: '737285476811',
    projectId: 'artefacts-615ee',
    authDomain: 'artefacts-615ee.firebaseapp.com',
    storageBucket: 'artefacts-615ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRW-siioz0WvoePPhJ_X-6XUkR-iPjPNM',
    appId: '1:737285476811:android:9e130bef715f26b673264e',
    messagingSenderId: '737285476811',
    projectId: 'artefacts-615ee',
    storageBucket: 'artefacts-615ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCETrpsjb17h80kEPH2eL2366O8pzy9fzc',
    appId: '1:737285476811:ios:9c073b763d82d82d73264e',
    messagingSenderId: '737285476811',
    projectId: 'artefacts-615ee',
    storageBucket: 'artefacts-615ee.firebasestorage.app',
    androidClientId: '737285476811-5sb9q6q84t37qtsa34583r4coq8jgirn.apps.googleusercontent.com',
    iosClientId: '737285476811-j63qd4n942g3dtaivlvap7s58krnb3qb.apps.googleusercontent.com',
    iosBundleId: 'com.example.artifact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCETrpsjb17h80kEPH2eL2366O8pzy9fzc',
    appId: '1:737285476811:ios:9c073b763d82d82d73264e',
    messagingSenderId: '737285476811',
    projectId: 'artefacts-615ee',
    storageBucket: 'artefacts-615ee.firebasestorage.app',
    androidClientId: '737285476811-5sb9q6q84t37qtsa34583r4coq8jgirn.apps.googleusercontent.com',
    iosClientId: '737285476811-j63qd4n942g3dtaivlvap7s58krnb3qb.apps.googleusercontent.com',
    iosBundleId: 'com.example.artifact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8SveKZiQ1U9c9ZI_jW5NZ6WHQBSp3DDo',
    appId: '1:737285476811:web:caf1ebcb37ff894773264e',
    messagingSenderId: '737285476811',
    projectId: 'artefacts-615ee',
    authDomain: 'artefacts-615ee.firebaseapp.com',
    storageBucket: 'artefacts-615ee.firebasestorage.app',
  );
}
